<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <Deterministic>true</Deterministic>
    <Version>0.4.4</Version>
    <RestorePackagesPath>$(MSBuildThisFileDirectory).tools\packages</RestorePackagesPath>
  </PropertyGroup>
  <Import Project="$(MSBuildThisFileDirectory)Local.props" Condition="Exists('$(MSBuildThisFileDirectory)Local.props')" />
</Project>
