<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\LiveRadio.Core\LiveRadio.Core.csproj" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Management" />
    <Compile Include="../../src/LiveRadio.Mod/StationArtwork.cs" Link="StationArtwork.cs" />
  </ItemGroup>
</Project>
